name: sublight_game
description: A game about management of resources on a colony starship.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flame: ^1.2.0
  flame_behaviors: ^0.1.0
  flame_bloc: ^1.5.0
  flame_stellaris:
    path: packages/flame_stellaris
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.1
  population_repository:
    path: packages/population_repository
  solar_system_repository:
    path: packages/solar_system_repository

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
