name: example
description: Example on how to use flame_stellaris

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dashbook: ^0.1.8
  flame: ^1.1.1
  flame_stellaris:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
